---
title: "ISCD Homework 6"
author: "Anurag Bhunia(bmat2508@isibang.ac.in)"
output: pdf_document
---

```{r setup, include=FALSE}
library(tidyverse)
library(viridisLite)
```

1.

a)

```{r}
x=c(13,40,23,15,21,4,44,16,32,14);
y=sort(unique(x));
z=numeric(length(y));
for(i in 1:length(y)){
    z[i]=sum(x==y[i]);
}
z=z/length(x);
f=ecdf(x)
#PMF
z
#ECDF
f
```

b)

```{r}
plot(y,z,main="PMF of given data");
plot(f,main="ECDF of given data");
```

2.

```{r}
N=c(50,100,200,300,400,500);
lm=numeric(length(N));
lv=numeric(length(N));
c=1;
for(i in N){
    x=rhyper(1000,50,i-50,20);
    y=1000/x[x!=0];
    m=mean(y);
    v=var(y);
    lm[c]=m;
    lv[c]=v;
    c=c+1
}
plot(N,lm,type="l",main="Mean sample size");
plot(N,lv,type="l",main="Variance of sample size");
```

4.

a) 

```{r}
n=100
N=20
p=0.4
x=rbinom(n,N,p)
m1=mean(x)
m2=mean(x^2)
Nhat=m1^2/(m1-(m2-m1^2))
phat=(m1-(m2-m1^2))/m1
Nhat
phat
```

b) 

```{r}
n=1000
N=20
p=0.4
x=rbinom(n,N,p)
m1=mean(x)
m2=mean(x^2)
Nhat=m1^2/(m1-(m2-m1^2))
phat=(m1-(m2-m1^2))/m1
Nhat
phat
```

c)

```{r}
n=100
N=10
p=0.1
x=rbinom(n,N,p)
m1=mean(x)
m2=mean(x^2)
Nhat=m1^2/(m1-(m2-m1^2))
phat=(m1-(m2-m1^2))/m1
Nhat
phat
n=100
N=10
p=0.9
x=rbinom(n,N,p)
m1=mean(x)
m2=mean(x^2)
Nhat=m1^2/(m1-(m2-m1^2))
phat=(m1-(m2-m1^2))/m1
Nhat
phat
n=1000
N=10
p=0.1
x=rbinom(n,N,p)
m1=mean(x)
m2=mean(x^2)
Nhat=m1^2/(m1-(m2-m1^2))
phat=(m1-(m2-m1^2))/m1
Nhat
phat
n=1000
N=10
p=0.9
x=rbinom(n,N,p)
m1=mean(x)
m2=mean(x^2)
Nhat=m1^2/(m1-(m2-m1^2))
phat=(m1-(m2-m1^2))/m1
Nhat
phat
```